export const tourListData = [
  {
    id: 1,
    title: 'Neelam Valley, Kashmir',
    duration: '3',
    availability: 'Jan 1-Jan 24',
    description:
      'Neelum valley is one of the beautiful places of Azad Kashmir and it’s named after the river which has curves like snake and has blue color. It is also called as the “PARASIDE OF KASHMIR”. There is a contradiction that this valley was named after a precious stone called Neelum. Neelum Valley is located in the Kashmir Region and to the North & the North East of Muzaffarabad and running parallel to the Kaghan Valley. It is different from it by snowstorm covered mountain which are 4000 meters higher than the ocean level. It contains about 370 large and small villages. It mostly contains hills and mountains with great valleys. The valley has thick forest, streams and rivers. This valley is dipped in most amazing beauty and attracts lots of tourists from within the country and other foreign countries as well. The valley can be approached from two different points. One from Kaghan Valley and the other is Noori Top. Besides these two it has many minor passes as well.',
    price: 11000,
    lat: 34.5985,
    long: 73.9073,
    departure: 'Lahore',
    arrival: 'Lahore',
    maxPeople: 25,
    bannerImage: '/assets/images/neelum.jpeg',
  },
  {
    id: 2,
    title: 'Shogran, Mansehra District, Khyber Pakhtunkhwa',
    duration: '5-7',
    availability: 'June 1-August 15',
    description:
      'Strolling through Shogran tranquilizing and soothing streets, breathing in the fresh air with a backdrop of snow-blanketed mountain peaks and foamy clouds, would be a mesmerizing experience. It offers a blend of picturesque tourist attractions and a soul-reviving environment. And it is home to River Kunhar and the sloping hills covered with puddles of sparkling water. Magnificent mountain peaks, including Makra Peak, Moosa Ka Musalla, Malika Parbat, and others, surround the Shogran Valley. Shogran is a beautiful hill station located 2,362 meters above sea level. It is situated in the mesmerizing valleys of Kaghan and is usually populated with tourists worldwide in the years hottest months',
    price: 13000,
    lat: 34.6398,
    long: 73.4607,
    departure: 'Lahore',
    arrival: 'Lahore',
    maxPeople: 25,
    bannerImage: '/assets/images/shogran.jpeg',
  },
  {
    id: 3,
    title: 'Naran & Kaghan Valley, Khyber Pakhtunkhwa',
    duration: '5-7',
    availability: 'May 1 - August 15',
    description:
      'Kaghan is a jewel among the many beautiful valleys in the Mansehra District of Hazara in the Khyber Pakhtunkhwa Province of Pakistan. This 160-kilometer long valley is the most popular summer holiday spot for both Pakistanis as well as foreigners. The valley features pine forests, alpine meadows, crystal clear lakes and cool mountain streams. Kunhar River, the main feature of the valley, is famous for its trout fish. Nestled along the banks of the river are the towns of Balakot, Paras, Mahandari, Kaghan and Naran. The local people are friendly and simple. Gujar nomads are one of the most interesting features of the Kaghan Valley. They take their herds of cattle to the high pastures of the upper Kaghan Valley in spring and bring them down again in autumn. While going to Kaghan you will find them camped along the road in their traditional tents or moving up and down the valley with their herd of pack animals, sheep and goats.',
    price: 15000,
    lat: 34.5417,
    long: 73.35,
    departure: 'Lahore',
    arrival: 'Lahore',
    maxPeople: 25,
    bannerImage: '/assets/images/kaghan.jpeg',
  },
  {
    id: 4,
    title: 'Neelam Valley, Kashmir',
    duration: '3',
    availability: 'Jan 1-Jan 24',
    description:
      'Neelum valley is one of the beautiful places of Azad Kashmir and it’s named after the river which has curves like snake and has blue color. It is also called as the “PARASIDE OF KASHMIR”. There is a contradiction that this valley was named after a precious stone called Neelum. Neelum Valley is located in the Kashmir Region and to the North & the North East of Muzaffarabad and running parallel to the Kaghan Valley. It is different from it by snowstorm covered mountain which are 4000 meters higher than the ocean level. It contains about 370 large and small villages. It mostly contains hills and mountains with great valleys. The valley has thick forest, streams and rivers. This valley is dipped in most amazing beauty and attracts lots of tourists from within the country and other foreign countries as well. The valley can be approached from two different points. One from Kaghan Valley and the other is Noori Top. Besides these two it has many minor passes as well.',
    price: 11000,
    lat: 34.5985,
    long: 73.9073,
    departure: 'Lahore',
    arrival: 'Lahore',
    maxPeople: 25,
    bannerImage: '/assets/images/neelum.jpeg',
  },
  {
    id: 5,
    title: 'Shogran, Mansehra District, Khyber Pakhtunkhwa',
    duration: '5-7',
    availability: 'June 1-August 15',
    description:
      'Strolling through Shogran tranquilizing and soothing streets, breathing in the fresh air with a backdrop of snow-blanketed mountain peaks and foamy clouds, would be a mesmerizing experience. It offers a blend of picturesque tourist attractions and a soul-reviving environment. And it is home to River Kunhar and the sloping hills covered with puddles of sparkling water. Magnificent mountain peaks, including Makra Peak, Moosa Ka Musalla, Malika Parbat, and others, surround the Shogran Valley. Shogran is a beautiful hill station located 2,362 meters above sea level. It is situated in the mesmerizing valleys of Kaghan and is usually populated with tourists worldwide in the years hottest months',
    price: 13000,
    lat: 34.6398,
    long: 73.4607,
    departure: 'Lahore',
    arrival: 'Lahore',
    maxPeople: 25,
    bannerImage: '/assets/images/shogran.jpeg',
  },
  {
    id: 6,
    title: 'Naran & Kaghan Valley, Khyber Pakhtunkhwa',
    duration: '5-7',
    availability: 'May 1 - August 15',
    description:
      'Kaghan is a jewel among the many beautiful valleys in the Mansehra District of Hazara in the Khyber Pakhtunkhwa Province of Pakistan. This 160-kilometer long valley is the most popular summer holiday spot for both Pakistanis as well as foreigners. The valley features pine forests, alpine meadows, crystal clear lakes and cool mountain streams. Kunhar River, the main feature of the valley, is famous for its trout fish. Nestled along the banks of the river are the towns of Balakot, Paras, Mahandari, Kaghan and Naran. The local people are friendly and simple. Gujar nomads are one of the most interesting features of the Kaghan Valley. They take their herds of cattle to the high pastures of the upper Kaghan Valley in spring and bring them down again in autumn. While going to Kaghan you will find them camped along the road in their traditional tents or moving up and down the valley with their herd of pack animals, sheep and goats.',
    price: 15000,
    lat: 34.5417,
    long: 73.35,
    departure: 'Lahore',
    arrival: 'Lahore',
    maxPeople: 25,
    bannerImage: '/assets/images/kaghan.jpeg',
  },
  {
    id: 7,
    title: 'Neelam Valley, Kashmir',
    duration: '3',
    availability: 'Jan 1-Jan 24',
    description:
      'Neelum valley is one of the beautiful places of Azad Kashmir and it’s named after the river which has curves like snake and has blue color. It is also called as the “PARASIDE OF KASHMIR”. There is a contradiction that this valley was named after a precious stone called Neelum. Neelum Valley is located in the Kashmir Region and to the North & the North East of Muzaffarabad and running parallel to the Kaghan Valley. It is different from it by snowstorm covered mountain which are 4000 meters higher than the ocean level. It contains about 370 large and small villages. It mostly contains hills and mountains with great valleys. The valley has thick forest, streams and rivers. This valley is dipped in most amazing beauty and attracts lots of tourists from within the country and other foreign countries as well. The valley can be approached from two different points. One from Kaghan Valley and the other is Noori Top. Besides these two it has many minor passes as well.',
    price: 11000,
    lat: 34.5985,
    long: 73.9073,
    departure: 'Lahore',
    arrival: 'Lahore',
    maxPeople: 25,
    bannerImage: '/assets/images/neelum.jpeg',
  },
  {
    id: 8,
    title: 'Shogran, Mansehra District, Khyber Pakhtunkhwa',
    duration: '5-7',
    availability: 'June 1-August 15',
    description:
      'Strolling through Shogran tranquilizing and soothing streets, breathing in the fresh air with a backdrop of snow-blanketed mountain peaks and foamy clouds, would be a mesmerizing experience. It offers a blend of picturesque tourist attractions and a soul-reviving environment. And it is home to River Kunhar and the sloping hills covered with puddles of sparkling water. Magnificent mountain peaks, including Makra Peak, Moosa Ka Musalla, Malika Parbat, and others, surround the Shogran Valley. Shogran is a beautiful hill station located 2,362 meters above sea level. It is situated in the mesmerizing valleys of Kaghan and is usually populated with tourists worldwide in the years hottest months',
    price: 13000,
    lat: 34.6398,
    long: 73.4607,
    departure: 'Lahore',
    arrival: 'Lahore',
    maxPeople: 25,
    bannerImage: '/assets/images/shogran.jpeg',
  },
  {
    id: 9,
    title: 'Naran & Kaghan Valley, Khyber Pakhtunkhwa',
    duration: '5-7',
    availability: 'May 1 - August 15',
    description:
      'Kaghan is a jewel among the many beautiful valleys in the Mansehra District of Hazara in the Khyber Pakhtunkhwa Province of Pakistan. This 160-kilometer long valley is the most popular summer holiday spot for both Pakistanis as well as foreigners. The valley features pine forests, alpine meadows, crystal clear lakes and cool mountain streams. Kunhar River, the main feature of the valley, is famous for its trout fish. Nestled along the banks of the river are the towns of Balakot, Paras, Mahandari, Kaghan and Naran. The local people are friendly and simple. Gujar nomads are one of the most interesting features of the Kaghan Valley. They take their herds of cattle to the high pastures of the upper Kaghan Valley in spring and bring them down again in autumn. While going to Kaghan you will find them camped along the road in their traditional tents or moving up and down the valley with their herd of pack animals, sheep and goats.',
    price: 15000,
    lat: 34.5417,
    long: 73.35,
    departure: 'Lahore',
    arrival: 'Lahore',
    maxPeople: 25,
    bannerImage: '/assets/images/kaghan.jpeg',
  },
]
